"""ingredient unique

Revision ID: 0ff8ee3c18cc
Revises: f89330e9c104
Create Date: 2025-07-12 00:12:43.845831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff8ee3c18cc'
down_revision: Union[str, Sequence[str], None] = 'f89330e9c104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients', ['ingredient'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    # ### end Alembic commands ###
