"""dishes bug fix

Revision ID: 79bc8fb239fc
Revises: 3343e382e6cd
Create Date: 2025-07-10 21:28:40.981357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bc8fb239fc'
down_revision: Union[str, Sequence[str], None] = '3343e382e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('ingredients_id', sa.Integer(), nullable=False),
    sa.Column('taste_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('free_choose', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_dish_name'), 'dishes', ['dish_name'], unique=True)
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.create_index(op.f('ix_dishes_series'), 'dishes', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dishes_series'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_dish_name'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
