"""fix relation

Revision ID: 7fba5c138671
Revises: acb351e39f7c
Create Date: 2025-07-11 23:31:38.902996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fba5c138671'
down_revision: Union[str, Sequence[str], None] = 'acb351e39f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_detail_order_id'), 'orders_detail', ['order_id'], unique=False)
    op.create_table('orders_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dining_table', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('order_time', sa.Date(), nullable=False),
    sa.Column('complete_time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_master_complete'), 'orders_master', ['complete'], unique=False)
    op.drop_index(op.f('ix_orders_dining_table'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.alter_column('dishes', 'score',
               existing_type=mysql.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_series'), table_name='dishes')
    op.drop_column('dishes', 'taste_id')
    op.drop_column('dishes', 'ingredients_id')
    op.add_column('ingredients', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.add_column('tastes', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tastes_id'), table_name='tastes')
    op.drop_index(op.f('taste'), table_name='tastes')
    op.create_index(op.f('ix_tastes_dish_id'), 'tastes', ['dish_id'], unique=False)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_index(op.f('ix_tastes_dish_id'), table_name='tastes')
    op.create_index(op.f('taste'), 'tastes', ['taste'], unique=True)
    op.create_index(op.f('ix_tastes_id'), 'tastes', ['id'], unique=False)
    op.drop_column('tastes', 'dish_id')
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.drop_column('ingredients', 'dish_id')
    op.add_column('dishes', sa.Column('ingredients_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dishes', sa.Column('taste_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_dishes_series'), 'dishes', ['series'], unique=False)
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.alter_column('dishes', 'score',
               existing_type=sa.FLOAT(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dining_table', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('dish_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_dining_table'), 'orders', ['dining_table'], unique=False)
    op.drop_index(op.f('ix_orders_master_complete'), table_name='orders_master')
    op.drop_table('orders_master')
    op.drop_index(op.f('ix_orders_detail_order_id'), table_name='orders_detail')
    op.drop_table('orders_detail')
    # ### end Alembic commands ###
