"""dishes bug fix

Revision ID: acb351e39f7c
Revises: c5fd14badd03
Create Date: 2025-07-10 21:37:47.754597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb351e39f7c'
down_revision: Union[str, Sequence[str], None] = 'c5fd14badd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tastes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taste', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taste')
    )
    op.create_index(op.f('ix_tastes_id'), 'tastes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tastes_id'), table_name='tastes')
    op.drop_table('tastes')
    # ### end Alembic commands ###
