"""internal multi to multi

Revision ID: f89330e9c104
Revises: 7fba5c138671
Create Date: 2025-07-11 23:56:00.161493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f89330e9c104'
down_revision: Union[str, Sequence[str], None] = '7fba5c138671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_ingredients_dish_id'), 'dishes_ingredients', ['dish_id'], unique=False)
    op.create_table('dishes_tastes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('taste_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_tastes_dish_id'), 'dishes_tastes', ['dish_id'], unique=False)
    op.drop_column('ingredients', 'dish_id')
    op.drop_index(op.f('ix_tastes_dish_id'), table_name='tastes')
    op.create_unique_constraint(None, 'tastes', ['taste'])
    op.drop_column('tastes', 'dish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tastes', sa.Column('dish_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tastes', type_='unique')
    op.create_index(op.f('ix_tastes_dish_id'), 'tastes', ['dish_id'], unique=False)
    op.add_column('ingredients', sa.Column('dish_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dishes_tastes_dish_id'), table_name='dishes_tastes')
    op.drop_table('dishes_tastes')
    op.drop_index(op.f('ix_dishes_ingredients_dish_id'), table_name='dishes_ingredients')
    op.drop_table('dishes_ingredients')
    # ### end Alembic commands ###
